version: '3.3'
services:
  authorization-server:
    container_name: authorization-server
    build:
      ./authorization-server
    image: authorization-server:latest
    expose:
      - 8091
    ports:
      - 8091:8091
    network_mode: host
    depends_on:
      - mysql-master
      - redis
      - mysql-slave
    volumes:
      - "./wait-for-it.sh:/tmp/wait-for-it.sh"
    command: ["./wait-for-it.sh", "mysql-master:3308", "java", "-jar" , "/authorization-server-0.0.1-SNAPSHOT.jar"]

  resource-server:
    container_name: resource-server
    build:
      ./resource-server
    image: resource-server:latest
    expose:
      - 8888
    ports:
      - 8888:8888
    network_mode: host
    depends_on:
      - mysql-master
      - redis
      - mysql-slave
    volumes:
      - "./wait-for-it.sh:/tmp/wait-for-it.sh"
    command: ["./tmp/wait-for-it.sh", "mysql-slave:3309", "--", "java", "-jar" , "/resource-server-0.0.1-SNAPSHOT.jar"]


  mysql-master:
    container_name: mysql-master
    image: 'mysql:5.7.15'
    restart: always
    ports:
      - '3308:3306'
    networks:
      - fullstack
    volumes:
      - type: bind
        source: ./mysql-master.cnf
        target: /etc/mysql/conf.d/mysql-master.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=baotrung
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=baotrung
    command: ["--log-bin=my"]

  mysql-slave:
    image: 'mysql:5.7.15'
    container_name: mysql-slave
    restart: always
    ports:
      - '3309:3306'
    networks:
      - fullstack
    volumes:
      - type: bind
        source: ./mysql-slave-1.cnf
        target: /etc/mysql/conf.d/mysql-slave-1.cnf
    depends_on:
      - mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  #    command: ["--skip-log-bin", "--skip-log-slave-updates", "--skip-slave-start"]

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
  mysqlnet:
    driver: bridge
volumes:
  redisdata:
    driver: "local"