version: '3.3'
services:
  #  db:
  #    image: mysql
  #    restart: always
  #    environment:
  #      MYSQL_DATABASE: 'baotrung'
  #      # So you don't have to use root, but you can if you like
  #      MYSQL_USER: 'baotrung'
  #      # You can use whatever password you like
  #      MYSQL_PASSWORD: '123456'
  #      # Password for root access
  #      MYSQL_ROOT_PASSWORD: '123456'
  #    ports:
  #      # <Port exposed> : < MySQL Port running inside container>
  #      - '3307:3306'
  #    expose:
  #      # Opens port 3306 on the container
  #      - '3307'
  #      # Where our data will be persisted
  #    volumes:
  #      - mysqldata:/var/lib/mysql
  #    networks:
  #      - fullstack
  authorization-server:
    container_name: authorization-server
    build:
      ./authorization-server
    image: authorization-server:latest
    expose:
      - 8091
    ports:
      - 8091:8091
    networks:
      - fullstack
    depends_on:
      - mysql-master
      - redis
      - mysql-slave
    volumes:
      - /data/springboot-docker-compose-authorization-server
    command: ["./wait-for-it.sh", "mysql-master:3308"]

  mysql-master:
    image: 'mysql:5.7'
    restart: always
    ports:
      - '3308:3306'
    networks:
      - fullstack
    volumes:
      - type: bind
        source: ./mysql-master.cnf
        target: /etc/mysql/conf.d/mysql-master.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=baotrung
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=baotrung
    command: ["--log-bin=my"]

  mysql-slave:
    image: 'mysql:5.7'
    restart: always
    ports:
      - '3309:3306'
    networks:
      - fullstack
    volumes:
      - type: bind
        source: ./mysql-slave-1.cnf
        target: /etc/mysql/conf.d/mysql-slave-1.cnf
    depends_on:
      - mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    command: ["--skip-log-bin", "--skip-log-slave-updates", "--skip-slave-start"]

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
  mysqlnet:
    driver: bridge
volumes:
  redisdata:
    driver: "local"