version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'baotrung'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'baotrung'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - fullstack
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
volumes:
  mysqldata:
  redisdata:
    driver: "local"