server:
  port: 8888

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.ashina.backend: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BaoTrung2?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
    show-sql: true

app:
  oauth2:
    client-id: myapp
    client-secret: secret
    resource-id: myapi
    token-info-uri: http://localhost:8901/oauth/check_token
