server:
  port: 8901

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/baotrung?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
#    timeout: 2000
jwt:
  signing-key: mykey

email:
  host: smtp.gmail.com
  port: 587
  username:
  password:
  auth: true
  smtp: smtp
  tls: true
  debug: true

cache:
  timeout: 60