server:
  port: 8901

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/baotrung?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: baotrung
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:

jwt:
  signing-key: mykey

email:
  host: smtp.gmail.com
  port: 587
  username:
  password:
  auth: true
  smtp: smtp
  tls: true
  debug: true
